### ISSUE TITLE
RESEARCH CICS Jobs

### ISSUE THREAD

**Issue by roundtr** [roundtr/SAS-SQL-Conversion#18]
- [x] CICD009

- [x] CICD0010

- [x] CICW0031

- [x] CICD0001

- [x] CICD0008

- [x] CICW0030

**Comment by grahaj7** [comment]
CICS team has reviewed these jobs at our Request and I expect a list of their findings the week of Aug 13

**Comment by roundtr** [comment]
Thanks for the update Jenny. 😊
[Nationwide is on your side.]

Rena Roundtreee
Specialist, Infrastructure Engineering
Mainframe Platform Engineering
Certified Scrum Master
W 614-427-4142 C 614-531-2155
roundtr@nationwide.com

FORTUNE® and Time Inc. are not affiliated with, and do not endorse the products or services of, Nationwide Mutual Insurance Company.

**Comment by roundtr** [comment]
Neat! I didn’t realize you would get emailed!

[cid:image001.png@01D432E1.43C0B480]

From: Roundtree, Rena
Sent: Monday, August 13, 2018 8:39 AM
To: roundtr/SAS-SQL-Conversion <reply@reply.github.com>; roundtr/SAS-SQL-Conversion <SAS-SQL-Conversion@noreply.github.com>; Graham, Jennifer K <grahaj7@nationwide.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [roundtr/SAS-SQL-Conversion] CICS Jobs (#18)


Thanks for the update Jenny. 😊
[Nationwide is on your side.]

Rena Roundtreee
Specialist, Infrastructure Engineering
Mainframe Platform Engineering
Certified Scrum Master
W 614-427-4142 C 614-531-2155
roundtr@nationwide.com<mailto:roundtr@nationwide.com>

FORTUNE® and Time Inc. are not affiliated with, and do not endorse the products or services of, Nationwide Mutual Insurance Company.

**Comment by grahaj7** [comment]
CICS Team has researched these jobs and provided a list of what can go and what needs to stay. Will create a new card for the jobs that need to be converted to some other software.
XA02
•	CICD0009 – can go away
•	CICD0010 – can go away
•	CICW0031 – needs converted

XA01
•	CICD0001 – can possibly go away depending on successor job CICD0002 (DB2)
•	CICD0008 – can go away
•	CICW0030 – needs converted

XA03
•	SYSD0007 – can possibly go away depending on successor job UTLD8004 (DB2)
