### ISSUE TITLE
RESEARCH - Alternatives to SAS

### ISSUE THREAD

**Issue by roundtr** [roundtr/SAS-SQL-Conversion#19]
Per John Mustric:
I’ve researched open source, and there is nothing available for our requirements.
Additionally, outside sources was contacted. One source that is highly trusted/experienced.  This source suggested numbers (1) and (2) below:
 
(1)	PC based SAS (as Tim also mentioned) with MXG, ie.,  PC SAS + MXG which he thought would be in the range of 5K / yr 
(2)	Easy/SMF  (might be less expensive than PC SAS +MXG) https://www.blackhillsoftware.com/easysmf/
(3)	Pacific System Group’s “Spectrum SMF Writer”.   Product description: http://www.pacsys.com/smf/    Product pricing http://www.pacsys.com/smf/smfprice.pdf

**Comment by mustrij** [comment]
BlackHillSoftware's EasySMF for z/OS product, but it does not meed our performance tower requirements to replace SAS.

Pacific System Group's 'Spectrum SMF Writer' has been installed for a 30 day trial.  Sample Test JCL has been created for some SMF type 30 generic  reporting.
