### ISSUE TITLE
Performance Engineering - Review jobs for SAS alternatives

### ISSUE THREAD

**Issue by roundtr** [roundtr/SAS-SQL-Conversion#25]
- [x] PRH020AL

**Comment by mustrij** [comment]
Reviewed/researched BlackHillSoftware's EasySMF for z/OS product, but it does not meed our requirements to replace SAS.

**Comment by mustrij** [comment]
The PRH020AL might belong to the capacity team, or it's possibly executed for Rodney Horn by the capacity team?  But it is not a performance tower job.

**Comment by mustrij** [comment]
..am going to make an attempt to "convert" PRH020AL from a batch SAS/DB2 job to Cognos  code on behalf of the capacity team.

**Comment by mustrij** [comment]
This job has been converted via Cognos.
